DROP TABLE IF EXISTS llamas;
DROP TABLE IF EXISTS lions;

CREATE TABLE llamas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INT CHECK (age > 0),
    weight TEXT
);

CREATE TABLE lions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INT CHECK (age > 0),
    weight TEXT
);
